create database db

use db

select * from customers

select * from orders

select * from restaurants

select c.customer_name,o.order_amount,o.payment_method from customers c
inner join orders o
on c.customer_id= o.customer_id
order by o.order_amount desc


1.Display all completed orders along with customer name and restaurant name


select c.customer_name,r.restaurant_name from orders o 
left join customers c on o.customer_id = o.customer_id
left  join restaurants r on r.restaurant_id = o.restaurant_id
where o.order_status = 'Completed'


2. Find the total revenue generated by each restaurant. 

select r.restaurant_name,sum(o.order_amount) as tot_amount from restaurants r
join orders o on o.restaurant_id = r.restaurant_id
group by r.restaurant_name
order by tot_amount desc

3.Show the total number of orders placed by each customer. 

select c.customer_name,count(o.order_id) as counts from customers c
join orders o  on o.customer_id = c.customer_id
group by c.customer_name
order by counts desc

4.Find the average order amount for each city. 


select c.city,sum(o.order_amount) as tot_amount from customers c
join orders o on o.customer_id = c.customer_id
group by c.city
order by tot_amount desc

5.Categorize orders as Low, Medium, and High based on order amount.

select order_id,
case 
when order_amount<400 then 'Low'
when order_amount>400 and order_amount<800 then 'mid'
else 'High'
end as 'order_cat' 

from orders o


6.Display restaurants whose average order value is greater than the overall average order value. 


with c as (
select r.restaurant_name,avg(o.order_amount) as avg_order_val from restaurants r
join orders o on o.restaurant_id = r.restaurant_id
group by r.restaurant_name
)
select restaurant_name from c
where avg_order_val >(select avg(order_amount) from orders)


7.Find customers who have never placed any orders. 

select c.customer_name    from customers c
join orders o on o.customer_id = c.customer_id
where o.order_id is null


8.Show the top 5 customers based on total spending. 

select top 5 c.customer_name,sum(o.order_amount) as tot_spent from customers c
join orders o on o.customer_id = c.customer_id
group by c.customer_name
order by tot_spent desc

9.Find the most frequently used payment method. 

select payment_method,count(*) as num from orders
group by payment_method
order by num desc

10.Calculate the running total of revenue by order date. 

select order_date,order_amount,sum(order_amount)over(partition by order_date order by order_date) as runn from orders


11.Rank restaurants based on total revenue generated. 
with c as (
select r.restaurant_name,sum(o.order_amount) as tot from restaurants r
join orders o 
on o.restaurant_id = r.restaurant_id
group by r.restaurant_name
)
select restaurant_name,DENSE_RANK()over(order by tot desc) as rank from c

12.Find the second highest order amount from the orders table. 

select  MAX(order_amount) as 'sec_max' from orders
where order_amount < (select max(order_amount) from orders)

13.Find customers who placed more orders than the average number of orders per customer. 

with c as (

select c.customer_name,count(o.order_id) as num_orders from customers c 
join orders o on o.customer_id = c.customer_id
group by c.customer_name
)
select customer_name from c
where num_orders > (select avg(num_orders) from c)


14.Display the top 3 restaurants in each city based on total orders received. 
with c as (
select c.city,r.restaurant_name, ROW_NUMBER()OVER(partition by c.city order by count(order_id) desc) as rank from orders o 
join customers c on o.customer_id = o.customer_id
join restaurants r on r.restaurant_id = o.restaurant_id
group by c.city,r.restaurant_name
) select city, restaurant_name,rank from c
where rank <=3

15.Calculate month-wise revenue and show the previous month revenue.

select month(order_date) as mon,sum(order_amount) as cur_mon,lag(sum(order_amount))over(order by month(order_date)) as prev from orders
group by month(order_date)